# Generated by Django 3.2.6 on 2021-08-26 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juego', '0003_pregunta_id_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='dificultad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
